// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: protos/sph_service.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SphService_GetSphDetails_FullMethodName = "/sph_service.SphService/GetSphDetails"
)

// SphServiceClient is the client API for SphService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SphServiceClient interface {
	GetSphDetails(ctx context.Context, in *GetSphDetailsRequest, opts ...grpc.CallOption) (*GetSphDetailsResponse, error)
}

type sphServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSphServiceClient(cc grpc.ClientConnInterface) SphServiceClient {
	return &sphServiceClient{cc}
}

func (c *sphServiceClient) GetSphDetails(ctx context.Context, in *GetSphDetailsRequest, opts ...grpc.CallOption) (*GetSphDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSphDetailsResponse)
	err := c.cc.Invoke(ctx, SphService_GetSphDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SphServiceServer is the server API for SphService service.
// All implementations must embed UnimplementedSphServiceServer
// for forward compatibility.
type SphServiceServer interface {
	GetSphDetails(context.Context, *GetSphDetailsRequest) (*GetSphDetailsResponse, error)
	mustEmbedUnimplementedSphServiceServer()
}

// UnimplementedSphServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSphServiceServer struct{}

func (UnimplementedSphServiceServer) GetSphDetails(context.Context, *GetSphDetailsRequest) (*GetSphDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSphDetails not implemented")
}
func (UnimplementedSphServiceServer) mustEmbedUnimplementedSphServiceServer() {}
func (UnimplementedSphServiceServer) testEmbeddedByValue()                    {}

// UnsafeSphServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SphServiceServer will
// result in compilation errors.
type UnsafeSphServiceServer interface {
	mustEmbedUnimplementedSphServiceServer()
}

func RegisterSphServiceServer(s grpc.ServiceRegistrar, srv SphServiceServer) {
	// If the following call pancis, it indicates UnimplementedSphServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SphService_ServiceDesc, srv)
}

func _SphService_GetSphDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSphDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SphServiceServer).GetSphDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SphService_GetSphDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SphServiceServer).GetSphDetails(ctx, req.(*GetSphDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SphService_ServiceDesc is the grpc.ServiceDesc for SphService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SphService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sph_service.SphService",
	HandlerType: (*SphServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSphDetails",
			Handler:    _SphService_GetSphDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/sph_service.proto",
}
